Gion Rubitschung D1P 30.09.23
# 12_Matrix_multiplication Problem 4

In [3]:
import numpy as np
from numpy.linalg import matrix_power

![img1](./images/img1.png)

In [4]:
M = np.array(
    [
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
    ]
)
v = np.array([[1], [2], [3], [4], [5]])
print(M @ v)

[[2]
 [3]
 [4]
 [5]
 [1]]


![img2](./images/img2.png)

In [5]:
print("M 2-th:")
print(matrix_power(M, 2))
print("M 3-th:")
print(matrix_power(M, 3))
print("M 4-th:")
print(matrix_power(M, 4))

M 2-th:
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]]
M 3-th:
[[0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
M 4-th:
[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


## a.

![img3](./images/img3.png)

In [6]:
M2 = matrix_power(M, 2)

print(M2 @ v)

[[3]
 [4]
 [5]
 [1]
 [2]]


## b.

![img4](./images/img4.png)

In [7]:
M5 = matrix_power(M, 5)

print(M5)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## c.

![img5](./images/img5.png)

In [8]:
M6 = matrix_power(M, 6)
M11 = matrix_power(M, 11)
M16 = matrix_power(M, 16)

print(np.array_equal(M, M6))
print(np.array_equal(M, M11))
print(np.array_equal(M, M16))

True
True
True


In [9]:
M4 = matrix_power(M, 4)
M19 = matrix_power(M, 19)

print(M4)
print(M19)
print(np.array_equal(M4, M19))

[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
True
