In [1]:
import numpy as np
from numpy.linalg import matrix_power

## a.
Give a similar description of $(A_n)^2$

$n = 3$

In [2]:
A = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])
matrix_power(A, 2)

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

$n = 5$

In [3]:
A = np.array(
    [
        [0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1],
        [1, 1, 1, 1, 0],
    ]
)
matrix_power(A, 2)

array([[4, 3, 3, 3, 3],
       [3, 4, 3, 3, 3],
       [3, 3, 4, 3, 3],
       [3, 3, 3, 4, 3],
       [3, 3, 3, 3, 4]])

$n = 11$

In [4]:
A = np.array(
    [
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    ]
)
matrix_power(A, 2)

array([[10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [ 9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [ 9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9],
       [ 9,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9],
       [ 9,  9,  9,  9, 10,  9,  9,  9,  9,  9,  9],
       [ 9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9],
       [ 9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9],
       [ 9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9],
       [ 9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10]])

## b.
Give a similar description of $(A_n)^3$

$n = 3$

In [5]:
A = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])
matrix_power(A, 3)

array([[2, 3, 3],
       [3, 2, 3],
       [3, 3, 2]])

$n = 5$

$A_{11} = 0*4 + 1*3 + 1*3 + 1*3 + 1*3 = 0 + 4*3 = (n - 1)(n- 2) = 12$

$A_{21} = 1*4 + 0*3 + 1*3 + 1*3 + 1*3 = 4 + 0 + 3*3 = (n - 1) + (n - 2)^2 = 13$

In [9]:
A = np.array(
    [
        [0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1],
        [1, 1, 1, 1, 0],
    ]
)
print(A)
print(matrix_power(A, 2))
matrix_power(A, 3)

[[0 1 1 1 1]
 [1 0 1 1 1]
 [1 1 0 1 1]
 [1 1 1 0 1]
 [1 1 1 1 0]]
[[4 3 3 3 3]
 [3 4 3 3 3]
 [3 3 4 3 3]
 [3 3 3 4 3]
 [3 3 3 3 4]]


array([[12, 13, 13, 13, 13],
       [13, 12, 13, 13, 13],
       [13, 13, 12, 13, 13],
       [13, 13, 13, 12, 13],
       [13, 13, 13, 13, 12]])

$n = 11$

In [8]:
A = np.array(
    [
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    ]
)
matrix_power(A, 3)

array([[72, 73, 73, 73, 73, 73, 73, 73, 73, 73],
       [73, 72, 73, 73, 73, 73, 73, 73, 73, 73],
       [73, 73, 72, 73, 73, 73, 73, 73, 73, 73],
       [73, 73, 73, 72, 73, 73, 73, 73, 73, 73],
       [73, 73, 73, 73, 72, 73, 73, 73, 73, 73],
       [73, 73, 73, 73, 73, 72, 73, 73, 73, 73],
       [73, 73, 73, 73, 73, 73, 72, 73, 73, 73],
       [73, 73, 73, 73, 73, 73, 73, 72, 73, 73],
       [73, 73, 73, 73, 73, 73, 73, 73, 72, 73],
       [73, 73, 73, 73, 73, 73, 73, 73, 73, 72]])