![p4](./p4.png)


In [1]:
import numpy as np

A = np.array([[1, 1, 0], [1, 0, 2], [-1, 1, -1], [0, 6, 1], [5, 1, 0]])
b = np.array([5, 7, 9, -4, 0])

In [2]:
A

array([[ 1,  1,  0],
       [ 1,  0,  2],
       [-1,  1, -1],
       [ 0,  6,  1],
       [ 5,  1,  0]])

In [3]:
b

array([ 5,  7,  9, -4,  0])

In [4]:
Q, R = np.linalg.qr(A)

In [5]:
Q

array([[-0.18898224,  0.13306585, -0.08956879],
       [-0.18898224, -0.02892736,  0.84285469],
       [ 0.18898224,  0.19092057, -0.45403534],
       [-0.        ,  0.97195925,  0.13084473],
       [-0.94491118,  0.01735642, -0.24146425]])

In [6]:
R

array([[-5.29150262, -0.94491118, -0.56694671],
       [ 0.        ,  6.17309832,  0.72318396],
       [ 0.        ,  0.        ,  2.27058944]])

In [7]:
f = np.linalg.inv(R) @ (Q.T @ b)
f

array([ 0.12452281, -0.31994183,  0.37102345])

In [8]:
f = np.linalg.solve(R, Q.T @ b)
f

array([ 0.12452281, -0.31994183,  0.37102345])

In [9]:
f = np.linalg.lstsq(A, b)[0]
f

/var/folders/ng/m_18wrfj7_ldv648sq9dh1km0000gn/T/ipykernel_66357/1992027921.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  f = np.linalg.lstsq(A, b)[0]


array([ 0.12452281, -0.31994183,  0.37102345])