In [29]:
import numpy as np

In [30]:
A = np.array([[0, 1], [1, 0]])
b = np.array([2, 3])
Q, R = np.linalg.qr(A)
print(f"A:\n{A}")
print(f"Q:\n{Q} (same as A)")
print(f"R:\n{R} (id. matrix)")

A:
[[0 1]
 [1 0]]
Q:
[[ 0. -1.]
 [-1.  0.]] (same as A)
R:
[[-1.  0.]
 [ 0. -1.]] (id. matrix)


In [31]:
x = np.linalg.inv(R) @ (Q.T @ b)
x

array([3., 2.])

In [32]:
x = A.T @ b
x

array([3, 2])