In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0, 0], [-1, 1, 0], [0, -1, 1], [0, 0, -1]])
b = np.array([0, 0, 1, 0])

In [3]:
Q, R = np.linalg.qr(A)
np.linalg.inv(R) @ (Q.T @ b)

array([-0.25, -0.5 ,  0.25])

In [4]:
np.linalg.inv(A.T @ A) @ A.T @ b

array([-0.25, -0.5 ,  0.25])

In [5]:
np.linalg.lstsq(A, b, rcond=None)[0]

array([-0.25, -0.5 ,  0.25])