In [75]:
import numpy as np
from numpy.linalg import qr, lstsq, norm, inv

![P1](./P1.png)

In [76]:
A = np.array(
    [
        [2, 3, 5],
        [7, 11, 13],
        [17, 19, 23],
        [29, 31, 37],
        [41, 43, 47],
    ]
)

b = np.array([2, 3, 5, 7, 11])

In [77]:
A

array([[ 2,  3,  5],
       [ 7, 11, 13],
       [17, 19, 23],
       [29, 31, 37],
       [41, 43, 47]])

In [78]:
b

array([ 2,  3,  5,  7, 11])

# a.

In [79]:
Q,R = qr(A)

In [80]:
Q

array([[-0.03737175, -0.22544052, -0.4133149 ],
       [-0.13080114, -0.92048761,  0.30741581],
       [-0.31765991, -0.20744934, -0.35214018],
       [-0.54189044,  0.01725685, -0.57987463],
       [-0.76612097,  0.24196304,  0.52384065]])

In [81]:
R

array([[-53.51635264, -57.32827161, -65.2510836 ],
       [  0.        ,  -3.80384986,  -5.85411024],
       [  0.        ,   0.        ,  -3.0042441 ]])

# b.

In [82]:
x = inv(R) @ (Q.T @ b)
x

array([-0.15186516,  0.40520192, -0.01266256])

# c.

In [83]:
e = norm((A @ x) - b)
e

1.4287791967814247

# d.

In [84]:
e_relative = e / norm(b)
e_relative

0.0990680126021477

# e.

In [85]:
x = lstsq(A, b)[0]
x

/var/folders/ng/m_18wrfj7_ldv648sq9dh1km0000gn/T/ipykernel_87406/4126771001.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x = lstsq(A, b)[0]


array([-0.15186516,  0.40520192, -0.01266256])