# Problem 2

![P2](./p2.png)


In [1]:
import sys
sys.path.insert(0, "..")

import numpy as np
from lib.matrix_operations import add_row, swap_row, multiply_row

In [2]:
M = np.array([[1, 1, 1, 1, 0], [1, 1, 0, 1, 1], [1, 0, 1, 1, 1]])

print("Starting matrix:")
print(M)

# Get clean C1
M = add_row(M, 1, 0, -1)
M = add_row(M, 2, 0, -1)

print("Clean C1:")
print(M)

M = swap_row(M, 1, 2)
M = multiply_row(M, 1, -1)
M = multiply_row(M, 2, -1)
M = add_row(M, 0, 1, -1)

print("Clean C2:")
print(M)

M = add_row(M, 0, 2, -1)

print("rref (clean C3):")
print(M)

Starting matrix:
[[1 1 1 1 0]
 [1 1 0 1 1]
 [1 0 1 1 1]]
Clean C1:
[[ 1  1  1  1  0]
 [ 0  0 -1  0  1]
 [ 0 -1  0  0  1]]
Clean C2:
[[ 1  0  1  1  1]
 [ 0  1  0  0 -1]
 [ 0  0  1  0 -1]]
rref (clean C3):
[[ 1  0  0  1  2]
 [ 0  1  0  0 -1]
 [ 0  0  1  0 -1]]
