In [37]:
# Needed for lib import, since it is a local module
import sys
sys.path.insert(0, "..")

import numpy as np
from lib.matrix_operations import add_row, swap_row, multiply_row
from numpy.linalg import det

In [38]:
A = lambda z: np.array([[1, 1, z, 0], [1, 1, 1, z], [0, 1, 1, 1], [0, 0, 1, 1]])
detA = lambda z: det(A(z))

## b.
$z = 0$ and $z = 5$

In [39]:
print(detA(5))
print(detA(0))

8.999999999999998
-1.0


## d.

$rref(A) | z = \dfrac{1}{2}$

In [40]:
A = A(0.5)
A

array([[1. , 1. , 0.5, 0. ],
       [1. , 1. , 1. , 0.5],
       [0. , 1. , 1. , 1. ],
       [0. , 0. , 1. , 1. ]])

### Clean C1

1. $A[0,0] = 1 \rightarrow pivot$
2. $R_2 \leftarrow R_2 - R_1$

In [41]:
A = add_row(A, 1, 0, -1, "float64")
A

array([[1. , 1. , 0.5, 0. ],
       [0. , 0. , 0.5, 0.5],
       [0. , 1. , 1. , 1. ],
       [0. , 0. , 1. , 1. ]])

### Clean C2

1. Swap $R_2 \leftrightarrow R_3$

In [42]:
A = swap_row(A, 1, 2, "float64")
A

array([[1. , 1. , 0.5, 0. ],
       [0. , 1. , 1. , 1. ],
       [0. , 0. , 0.5, 0.5],
       [0. , 0. , 1. , 1. ]])

2. $A[1,1] = 1 \rightarrow pivot$
3. $R_1 \leftarrow R_1 - R_2$

In [43]:
A = add_row(A, 0, 1, -1, "float64")
A

array([[ 1. ,  0. , -0.5, -1. ],
       [ 0. ,  1. ,  1. ,  1. ],
       [ 0. ,  0. ,  0.5,  0.5],
       [ 0. ,  0. ,  1. ,  1. ]])

### Clean C3

1. Swap $R_3 \leftrightarrow R_4$

In [44]:
A = swap_row(A, 2, 3, "float64")
A

array([[ 1. ,  0. , -0.5, -1. ],
       [ 0. ,  1. ,  1. ,  1. ],
       [ 0. ,  0. ,  1. ,  1. ],
       [ 0. ,  0. ,  0.5,  0.5]])

2. $A[2,2] = 1 \rightarrow pivot$
3. $R_4 \leftarrow R_4 - \dfrac{1}{2}R_3$
4. $R_2 \leftarrow R_2 - R_3$
5. $R_1 \leftarrow R_1 + \dfrac{1}{2}R_3$

In [45]:
A = add_row(A, 3, 2, -0.5, "float64")
A = add_row(A, 1, 2, -1, "float64")
A = add_row(A, 0, 2, 0.5, "float64")
A

array([[ 1. ,  0. ,  0. , -0.5],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ]])

$$
\underline{\underline{
null(A)=
\left\{
\begin{pmatrix}
    0.5 \\
    0 \\
    -1 \\
    1
\end{pmatrix}
\right\}
}}
$$