In [1]:
# Needed for lib import, since it is a local module
import sys

sys.path.insert(0, "..")

from lib.matrix_operations import add_row, multiply_row
import numpy as np

Set
$$
F=\begin{pmatrix}
1 & 2 & 3 & 4 & 5 \\
2 & 3 & 4 & 5 & 6 \\
3 & 4 & 5 & 6 & 7 \\
4 & 5 & 6 & 7 & 8 \\
5 & 6 & 7 & 8 & 9
\end{pmatrix}
$$


In [2]:
F = np.array(
    [
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9],
    ]
)
print(F)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


# a.

Compute the $rref(F)$, with all-zero rows dropped.


## Clean C1

1. $F[0, 0] = 1 \rightarrow pivot$
2. $R_1 \leftarrow R_1 - 2R_0$
3. $R_2 \leftarrow R_2 - 3R_0$
4. $R_3 \leftarrow R_3 - 4R_0$
5. $R_4 \leftarrow R_4 - 5R_0$


In [3]:
F = add_row(F, 1, 0, -2)
F = add_row(F, 2, 0, -3)
F = add_row(F, 3, 0, -4)
F = add_row(F, 4, 0, -5)
print(F)

[[  1   2   3   4   5]
 [  0  -1  -2  -3  -4]
 [  0  -2  -4  -6  -8]
 [  0  -3  -6  -9 -12]
 [  0  -4  -8 -12 -16]]


## Clean C2

1. $R_1 \dots R_4 \leftarrow (-1)(R_1 \dots R_4)$


In [4]:
F = multiply_row(F, 1, -1)
F = multiply_row(F, 2, -1)
F = multiply_row(F, 3, -1)
F = multiply_row(F, 4, -1)
print(F)

[[ 1  2  3  4  5]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


2. $F[1, 1] = 1 \rightarrow pivot$
3. $R_0 \leftarrow R_0 - 2R_1$
4. $R_2 \leftarrow R_2 - 2R_1$
5. $R_3 \leftarrow R_3 - 3R_1$
6. $R_4 \leftarrow R_4 - 4R_1$


In [5]:
F = add_row(F, 0, 1, -2)
F = add_row(F, 2, 1, -2)
F = add_row(F, 3, 1, -3)
F = add_row(F, 4, 1, -4)
print(F)

[[ 1  0 -1 -2 -3]
 [ 0  1  2  3  4]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


$rref(F)$, with all-zero rows dropped ->
$$
\underline{\underline{
    rref(F)=\begin{pmatrix}
    1 & 0 & -1 & -2 & -3 \\\
    0 & 1 & 2 & 3 & 4
    \end{pmatrix}
}}
$$


# b.

Compute the $rank(F)$

$$rref(F) \rightarrow 2  pivots \Rightarrow \underline{\underline{rank(F) = 2}}$$


# c.

Compute a basis of the nullspace of $F$

$$
\underline{\underline{
null(F)=
\left\{
\begin{pmatrix}
    1 \\
    2 \\
    1 \\
    0 \\
    0
\end{pmatrix},
\begin{pmatrix}
    2 \\
    -3 \\
    0 \\
    1 \\
    0
\end{pmatrix},
\begin{pmatrix}
    3 \\
    -4 \\
    0 \\
    0 \\
    1
\end{pmatrix}
\right\}
}}
$$


# d.

Compute a basis of the column space of $F$.

$$F \rightarrow \mathbb{R}^5$$

$$null(F) \rightarrow \mathbb{R}^3$$

$$dim(colsp(F)) = dim(F) - dim(null(F)) = 5 - 3 = 2 \Rightarrow colsp(F) \rightarrow \mathbb{R}^2$$

## Transpose of $F$

$$
F=\begin{pmatrix}
1 & 2 & 3 & 4 & 5 \\
2 & 3 & 4 & 5 & 6 \\
3 & 4 & 5 & 6 & 7 \\
4 & 5 & 6 & 7 & 8 \\
5 & 6 & 7 & 8 & 9
\end{pmatrix}
\Rightarrow
F^T = \begin{pmatrix}
1 & 2 & 3 & 4 & 5 \\
2 & 3 & 4 & 5 & 6 \\
3 & 4 & 5 & 6 & 7 \\
4 & 5 & 6 & 7 & 8 \\
5 & 6 & 7 & 8 & 9
\end{pmatrix} = F
$$

## rref of $F^T$

Since
$$F = F^T \Rightarrow
rref(F) = rref(F^T) = \begin{pmatrix}
1 & 0 & -1 & -2 & -3 \\\
0 & 1 & 2 & 3 & 4
\end{pmatrix}
$$

## Basis of columspace $F$

$$
\underline{\underline{
colsp(F)=
\left\{
\begin{pmatrix}
    1 \\
    0 \\
    -1 \\
    -2 \\
    -3
\end{pmatrix},
\begin{pmatrix}
    0 \\
    1 \\
    2 \\
    3 \\
    4
\end{pmatrix}
\right\}
}}
$$


###
