In [131]:
# Needed for lib import, since it is a local module
import sys

sys.path.insert(0, "..")

from lib.matrix_operations import add_row, swap_row, multiply_row
import numpy as np

Set
$
F=\begin{pmatrix}
1 & 5 & 34 & 233 \\\
1 & 8 & 55 & 377 \\\
2 & 13 & 89 & 610 \\\
3 & 21 & 144 & 987
\end{pmatrix}
$


In [132]:
F = np.array([[1, 5, 34, 233], [1, 8, 55, 377], [2, 13, 89, 610], [3, 21, 144, 987]])
print(F)

[[  1   5  34 233]
 [  1   8  55 377]
 [  2  13  89 610]
 [  3  21 144 987]]


# a.

Compute the $rref(F)$, with all-zero rows dropped.


## Clean C1

1. $F[0, 0] \rightarrow pivot$
2. $R_1 \leftarrow R_1 - R_0$
3. $R_2 \leftarrow R_2 - 2R_0$
4. $R_3 \leftarrow R_3 - 3R_0$


In [133]:
F = add_row(F, 1, 0, -1)
F = add_row(F, 2, 0, -2)
F = add_row(F, 3, 0, -3)
print(F)

[[  1   5  34 233]
 [  0   3  21 144]
 [  0   3  21 144]
 [  0   6  42 288]]


## Clean C2

1. $R_3 \leftarrow \dfrac{1}{2}R_3$


In [134]:
F = multiply_row(F, 3, 0.5)
print(F)

[[  1   5  34 233]
 [  0   3  21 144]
 [  0   3  21 144]
 [  0   3  21 144]]


2. $R_1 ... R_3 \leftarrow \dfrac{1}{3}(R_1 ... R_3)$


In [135]:
F = multiply_row(F, 1, 1 / 3)
F = multiply_row(F, 2, 1 / 3)
F = multiply_row(F, 3, 1 / 3)
print(F)

[[  1   5  34 233]
 [  0   1   7  48]
 [  0   1   7  48]
 [  0   1   7  48]]


3. $F[1, 1] \rightarrow pivot$
4. $R_0 \leftarrow R_0 - 5R_1$
5. $R_2 \leftarrow R_2 - R_1$
6. $R_3 \leftarrow R_3 - R_1$


In [136]:
F = add_row(F, 0, 1, -5)
F = add_row(F, 2, 1, -1)
F = add_row(F, 3, 1, -1)
print(F)

[[ 1  0 -1 -7]
 [ 0  1  7 48]
 [ 0  0  0  0]
 [ 0  0  0  0]]


$rref(F)$, with all-zero rows dropped -> $
\underline{\underline{
    rref(F)=\begin{pmatrix}
    1 & 0 & -1 & -7 \\\
    0 & 1 & 7 & 48
    \end{pmatrix}
}}
$


# b.

Compute the $rank(F)$

$rref(F) \rightarrow 2 pivots \Rightarrow rank(F) = 2$


# c.

Compute a basis of the nullspace of $F$

$
\underline{\underline{
null(F)=
\left\{
\begin{pmatrix}
    1 \\
    -7 \\
    1 \\
    0
\end{pmatrix},
\begin{pmatrix}
    7 \\
    -48 \\
    0 \\
    1
\end{pmatrix}
\right\}
}}
$


# d.

Compute a basis of the column space of $F$.

$F \rightarrow \mathbb{R}^4$

$null(F) \rightarrow \mathbb{R}^2$

$dim(colsp(F)) = dim(F) - dim(null(F)) = 4 - 2 = 2 \Rightarrow colsp(F) \rightarrow \mathbb{R}^2$

## Transpose of $F$

$
F=\begin{pmatrix}
1 & 5 & 34 & 233 \\\
1 & 8 & 55 & 377 \\\
2 & 13 & 89 & 610 \\\
3 & 21 & 144 & 987
\end{pmatrix}
\Rightarrow
F^T = E = \begin{pmatrix}
1 & 1 & 2 & 3 \\\
5 & 8 & 13 & 21 \\\
34 & 55 & 89 & 144 \\\
233 & 377 & 610 & 987
\end{pmatrix}
$

## rref of $F^T$


In [137]:
E = np.array([[1, 1, 2, 3], [5, 8, 13, 21], [34, 55, 89, 144], [233, 377, 610, 987]])
print(E)

[[  1   1   2   3]
 [  5   8  13  21]
 [ 34  55  89 144]
 [233 377 610 987]]


### Clean C1

1. $E[0,0] \rightarrow pivot$
2. $R_1 \leftarrow R_1 - 5R_0$
3. $R_2 \leftarrow R_2 - 34R_0$
4. $R_3 \leftarrow R_3 - 233R_0$

In [138]:
E = add_row(E, 1, 0, -5)
E = add_row(E, 2, 0, -34)
E = add_row(E, 3, 0, -233)
print(E)

[[  1   1   2   3]
 [  0   3   3   6]
 [  0  21  21  42]
 [  0 144 144 288]]


### Clean C2

1. $R_1 ... R_3 \leftarrow \dfrac{1}{3}(R_1 ... R_3)$

In [139]:
E = multiply_row(E, 1, 1/3)
E = multiply_row(E, 2, 1/3)
E = multiply_row(E, 3, 1/3)
print(E)

[[ 1  1  2  3]
 [ 0  1  1  2]
 [ 0  7  7 14]
 [ 0 48 48 96]]


2. $R_0 \leftarrow R_0 -  R_1$
3. $R_2 \leftarrow R_2 - 7R_1$
4. $R_3 \leftarrow R_3 - 48R_1$

In [140]:
E = add_row(E, 0, 1, -1)
E = add_row(E, 2, 1, -7)
E = add_row(E, 3, 1, -48)
print(E)

[[1 0 1 1]
 [0 1 1 2]
 [0 0 0 0]
 [0 0 0 0]]


$
rref(E)=\begin{pmatrix}
1 & 0 & 1 & 1 \\\
0 & 1 & 1 & 2
\end{pmatrix}
$

## Basis of columspace $F$

$
\underline{\underline{
colsp(F)=
\left\{
\begin{pmatrix}
    1 \\
    0 \\
    1 \\
    1
\end{pmatrix},
\begin{pmatrix}
    0 \\
    1 \\
    1 \\
    2
\end{pmatrix}
\right\}
}}
$

### 