In [1]:
import numpy as np
from numpy.linalg import inv, solve

A = np.array(
    [
        [1, -1, -1, -1, 0, 1],
        [0, -1, 0, 0, 1, 1],
        [1, -1, 1, -1, 0, -1],
        [-1, 0, -1, 0, -1, -1],
        [1, 0, 1, 1, 1, 0],
        [-1, 0, 1, 1, 1, 1],
    ]
)

b = np.array([[1], [2], [3], [4], [5], [6]])

## a.
Compute the inverse matrix of $A$.

In [2]:
print(inv(A))
print(A @ inv(A))

[[ 0.5 -0.5  0.   0.   0.5  0. ]
 [-1.   0.5 -0.5 -1.  -0.5 -1. ]
 [ 0.5 -1.   0.5  0.   0.   1. ]
 [ 1.  -1.   0.   1.   1.   1. ]
 [-2.   2.5 -0.5 -1.  -0.5 -2. ]
 [ 1.  -1.   0.   0.   0.   1. ]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


## b.
Compute the solution $x$ to $Ax = b$ using `inv`

In [3]:
x = inv(A) @ b
print(x)
print(A @ x == b)

[[  2.]
 [-14.]
 [  6.]
 [ 14.]
 [-17.]
 [  5.]]
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


# c.
Compute the solution $x$ to $Ax = b$ in Python using `solve`

In [4]:
x = solve(A, b)
print(x)
print(A @ x == b)

[[  2.]
 [-14.]
 [  6.]
 [ 14.]
 [-17.]
 [  5.]]
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


## d.
See in previous prints